// Barrel export — import all interfaces from '@/interfaces'
export type { GamePhase, ArchiveDomain, NPCId, LocationId, InsightCardId, JournalThreadId, QuestId, MoralAlignment, AudioCategory, NPCAttitude, EndingId, ItemId, AchievementId } from './types.js'
export type { IGameState, IPlayerState, INPCState, IDialogueState, IDialogueChoice, WeatherType } from './IGameState.js'
export type { IAudioProvider, PlayOptions } from './IAudioProvider.js'
export type { IRenderer, RenderContext } from './IRenderer.js'
export type { II18n } from './II18n.js'
export type { ISystem } from './ISystem.js'
export type { IEventBus, IGameEvent, GameEventType, EventHandler } from './IEventBus.js'
export type { IEntity, IInteractable, EntityType } from './IEntity.js'
